-- Example 1 - Query 1
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
    SELECT *
    FROM Empleado
    WAITFOR DELAY '00:00:15'
    SELECT *
    FROM Empleado
    ROLLBACK

-- Example 2 - Query 1
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
    SELECT *
    FROM Empleado
    WHERE IdEmpleado BETWEEN 1 AND 25
    WAITFOR DELAY '00:00:15'
    SELECT *
    FROM Empleado
    WHERE IdEmpleado BETWEEN 1 AND 25
    ROLLBACK

